spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello_store
    username: user
    password: password
    hikari:
      maximum-pool-size: 100
  sql:
    init:
      schema-locations: classpath*:schema.sql
      mode: always
logging:
  level:
    org.hibernate.SQL: DEBUG
